#!/usr/bin/env bash
set -x

function mongodb_install
{
	brew update
	brew install mongodb
}
function mongodb_start
{
	mongod --config /usr/local/etc/mongod.conf
}
function mongodb_ruby
{
	gem update --system
	gem install mongo
	gem install bson
	gem install bson_ext
}
function es_install
{
	brew update
	brew install elasticsearch
}
function es_start
{
	elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml
}
${1}_${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}