#!/usr/bin/env bash
set -x

function mongodb_install
{
	brew update
	brew install mongodb
}
function mongodb_start
{
	mongod --config /usr/local/etc/mongod.conf
}
function mongodb_ruby
{
	gem update --system
	gem install mongo
	gem install bson
	gem install bson_ext
}
function es_install
{
	brew update
	brew install elasticsearch
}
function es_start
{
	elasticsearch --config=/usr/local/opt/elasticsearch/config/elasticsearch.yml
}
function ssh-copy-id_install
{
	brew update
	brew install ssh-copy-id
}
function ruby_db2
{
	export IBM_DB_HOME=${HOME}/sqllib
	gem install ibm_db
}
function ruby_install
{
	curl https://raw.github.com/fesplugas/rbenv-installer/master/bin/rbenv-installer | bash
	rbenv install 2.1.0
	rbenv global 2.1.0
	gem update --system


	gem install bundler 
	gem install pry
	gem install byebug
	gem install json
	gem install watir-webdriver
	gem install rails
}
${1}_${2} ${3} ${4} ${5} ${6} ${7} ${8} ${9}